import { ARM9 } from "./catalogos/procesadores/arm9";
import { H700 } from "./catalogos/procesadores/h700";
import { MTKD1100 } from "./catalogos/procesadores/mktD1100";
import { RK3326 } from "./catalogos/procesadores/rk3326";
import { RK3566_Android } from "./catalogos/procesadores/rk3566_android";
import { RK3566_Linux } from "./catalogos/procesadores/rk3566_linux";
import { SND8Gen2 } from "./catalogos/procesadores/snapdragon8gen2";
import { T310 } from "./catalogos/procesadores/t310";
import { T618 } from "./catalogos/procesadores/t618";
import { T820 } from "./catalogos/procesadores/t820";
import { Coleccion5ta, Coleccion8y16Bits, ColeccionFull } from "./collections";
import { Consola } from "./consola";
import fs from 'fs';

export const consolas: Array<Consola> = [
    {
        nombre: "RG35XX SP",
        fabricante: "Anbernic",
        formato: "Flip",
        pantallaPulgadas: 3.5,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3300,
        procesador: "H700",
        ram: 1,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: H700,
        joysticks: 0,
        tactil: false,
        sistemaOperativoStock: "Linux (Anbernic)",
        cfwCompatibles: ["Batocera", "Knulli", "muOS"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_Dl7BIjz",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DmIxVgF",
        img: "35xxsp",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },
    {
        nombre: "RG35XX H",
        fabricante: "Anbernic",
        formato: "Horizontal",
        pantallaPulgadas: 3.5,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3300,
        procesador: "H700",
        ram: 1,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: H700,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Linux (Anbernic)",
        cfwCompatibles: ["Batocera", "Knulli", "muOS"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DeS4BXv",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DCEqcyP",
        img: "35xxh",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },
    {
        nombre: "RG35XX Plus",
        fabricante: "Anbernic",
        formato: "Vertical",
        pantallaPulgadas: 3.5,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3300,
        procesador: "H700",
        ram: 1,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: H700,
        joysticks: 0,
        tactil: false,
        sistemaOperativoStock: "Linux (Anbernic)",
        cfwCompatibles: ["Batocera", "Knulli", "muOS"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_Ddt4Wjd",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DEWRVWr",
        img: "35xxplus",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },
    {
        nombre: "RG40XX H",
        fabricante: "Anbernic",
        formato: "Horizontal",
        pantallaPulgadas: 4,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3200,
        procesador: "H700",
        ram: 1,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: H700,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Linux (Anbernic)",
        cfwCompatibles: ["Batocera", "Knulli", "muOS"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DloVd95",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_Dlql5iR",
        img: "35xxh",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    // ANBERNIC RK3566
    {
        nombre: "RG353 VS",
        fabricante: "Anbernic",
        formato: "Vertical",
        pantallaPulgadas: 3.5,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3500,
        procesador: "RK3566",
        ram: 1,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3566_Linux,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Linux (Anbernic)",
        cfwCompatibles: ["ArkOS", "RockNix"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DBDyo5t",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_Dk9B53v",
        img: "353vs",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },
    {
        nombre: "RG353 PS",
        fabricante: "Anbernic",
        formato: "Horizontal",
        pantallaPulgadas: 3.5,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3500,
        procesador: "RK3566",
        ram: 1,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3566_Linux,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Linux (Anbernic)",
        cfwCompatibles: ["ArkOS", "RockNix"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DepmkPl",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DeIHBPD",
        img: "353ps",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    {
        nombre: "RG ARC-S",
        fabricante: "Anbernic",
        formato: "Horizontal",
        pantallaPulgadas: 4,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3500,
        procesador: "RK3566",
        ram: 1,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3566_Linux,
        joysticks: 0,
        tactil: false,
        sistemaOperativoStock: "Linux (Anbernic)",
        cfwCompatibles: ["ArkOS", "RockNix"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DmVbAJz",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DdXQ863",
        img: "arcs",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    {
        nombre: "RG ARC-D",
        fabricante: "Anbernic",
        formato: "Horizontal",
        pantallaPulgadas: 4,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3500,
        procesador: "RK3566",
        ram: 2,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "N64 / DC",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3566_Android,
        joysticks: 0,
        tactil: true,
        sistemaOperativoStock: "Linux (Anbernic) / Android 11",
        cfwCompatibles: ["ArkOS", "RockNix"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DnLqfOR",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DBSiTjD",
        img: "arcs",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },


    {
        nombre: "RG353 V",
        fabricante: "Anbernic",
        formato: "Horizontal",
        pantallaPulgadas: 4,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3500,
        procesador: "RK3566",
        ram: 2,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "N64 / DC",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3566_Android,
        joysticks: 2,
        tactil: true,
        sistemaOperativoStock: "Linux (Anbernic) / Android 11",
        cfwCompatibles: ["ArkOS", "RockNix"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DBDyo5t",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_Dk9B53v",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true,
        img: "353vs"
    },

    {
        nombre: "RG353 P",
        fabricante: "Anbernic",
        formato: "Horizontal",
        pantallaPulgadas: 4,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3500,
        procesador: "RK3566",
        ram: 2,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "N64 / DC",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3566_Android,
        joysticks: 2,
        tactil: true,
        sistemaOperativoStock: "Linux (Anbernic) / Android 11",
        cfwCompatibles: ["ArkOS", "RockNix"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_Dk5aLOn",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DCf4olZ",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true,
        img: "353p"
    },

    {
        nombre: "RG505",
        fabricante: "Anbernic",
        formato: "Horizontal",
        pantallaPulgadas: 4.95,
        pantallaRelacionAspecto: "16:9",
        pantallaResolucion: "960x544",
        bateria: 5000,
        procesador: "T618",
        ram: 4,
        hdmi: false,
        bt: true,
        wifi: true,
        dobleSlot: false,
        almInterno: 128,
        almExterno: 1000,
        plataformaPerfectaMax: "PSP/N64/DC",
        plataformasEmulables: ColeccionFull,
        plataformasEmulablesSemaforo: T618,
        joysticks: 2,
        tactil: true,
        sistemaOperativoStock: "Android 12",
        cfwCompatibles: ["Gamma OS"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DCa2fJh",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DFXOGqF",
        img: "505",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },
    {
        nombre: "RG405V",
        fabricante: "Anbernic",
        formato: "Vertical",
        pantallaPulgadas: 4,
        pantallaRelacionAspecto: "16:9",
        pantallaResolucion: "640x480",
        bateria: 5500,
        procesador: "T618",
        ram: 4,
        hdmi: false,
        bt: true,
        wifi: true,
        dobleSlot: false,
        almInterno: 128,
        almExterno: 1000,
        plataformaPerfectaMax: "PSP/N64/DC",
        plataformasEmulables: ColeccionFull,
        plataformasEmulablesSemaforo: T618,
        joysticks: 2,
        tactil: true,
        sistemaOperativoStock: "Android 12",
        cfwCompatibles: ["Gamma OS"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DD7986r",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DeYeiNz",
        img: "405v",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    {
        nombre: "RG556",
        fabricante: "Anbernic",
        formato: "Horizontal",
        pantallaPulgadas: 5.48,
        pantallaRelacionAspecto: "16:9",
        pantallaResolucion: "1920x1080",
        bateria: 5500,
        procesador: "T820",
        ram: 8,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: false,
        almInterno: 128,
        almExterno: 1000,
        plataformaPerfectaMax: "PSP/N64/DC",
        plataformasEmulables: ColeccionFull,
        plataformasEmulablesSemaforo: T820,
        joysticks: 2,
        tactil: true,
        sistemaOperativoStock: "Android 13",
        cfwCompatibles: [],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DcwCa5N",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DFY5m2f",
        img: "556",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    {
        nombre: "RG Cube",
        fabricante: "Anbernic",
        formato: "Horizontal",
        pantallaPulgadas: 3.95,
        pantallaRelacionAspecto: "1:1",
        pantallaResolucion: "720x720",
        bateria: 5200,
        procesador: "T820",
        ram: 8,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: false,
        almInterno: 128,
        almExterno: 1000,
        plataformaPerfectaMax: "PSP/N64/DC",
        plataformasEmulables: ColeccionFull,
        plataformasEmulablesSemaforo: T820,
        joysticks: 2,
        tactil: true,
        sistemaOperativoStock: "Android 13",
        cfwCompatibles: [],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DBr0omX",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DCLuHEF",
        img: "cube",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    /**********************
    
    POWKIDDY
    
    **/

    {
        nombre: "RGB20S",
        fabricante: "Powkiddy",
        formato: "Vertical",
        pantallaPulgadas: 3.5,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3500,
        procesador: "RK3326",
        ram: 1,
        hdmi: false,
        bt: false,
        wifi: false,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3326,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Linux",
        cfwCompatibles: ["ArkOS", "AmberElec"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DkHPu3v",
        enlaceDeCompra2: "",
        img: "rgb20s",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    {
        nombre: "V10",
        fabricante: "Powkiddy",
        formato: "Vertical",
        pantallaPulgadas: 3.5,
        pantallaRelacionAspecto: "3:2",
        pantallaResolucion: "480x320",
        bateria: 3000,
        procesador: "RK3326",
        ram: 1,
        hdmi: false,
        bt: false,
        wifi: false,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3326,
        joysticks: 0,
        tactil: false,
        sistemaOperativoStock: "Linux",
        cfwCompatibles: ["ArkOS", "AmberElec"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DDeDRzh",
        enlaceDeCompra2: "",
        img: "v10",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    {
        nombre: "V90",
        fabricante: "Powkiddy",
        formato: "Flip",
        pantallaPulgadas: 3,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "320x240",
        bateria: 1029,
        procesador: "ARM9",
        ram: 0,
        hdmi: false,
        bt: false,
        wifi: false,
        dobleSlot: false,
        almInterno: 0,
        almExterno: 128,
        plataformaPerfectaMax: "PlayStation 1",
        plataformasEmulables: Coleccion8y16Bits,
        plataformasEmulablesSemaforo: ARM9,
        joysticks: 0,
        tactil: false,
        sistemaOperativoStock: "Linux",
        cfwCompatibles: [],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DcRvvaT",
        enlaceDeCompra2: "",
        img: "v90",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    {
        nombre: "RGB10 MAX 3",
        fabricante: "Powkiddy",
        formato: "Horizontal",
        pantallaPulgadas: 5,
        pantallaRelacionAspecto: "16:9",
        pantallaResolucion: "1280x720",
        bateria: 4000,
        procesador: "RK3566",
        ram: 1,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3566_Linux,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Linux",
        cfwCompatibles: ["ArkOS", "AmberElec"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DDqCort",
        enlaceDeCompra2: "",
        img: "rgb10max3",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    {
        nombre: "X55",
        fabricante: "Powkiddy",
        formato: "Horizontal",
        pantallaPulgadas: 5.5,
        pantallaRelacionAspecto: "16:9",
        pantallaResolucion: "1280x720",
        bateria: 4000,
        procesador: "RK3566",
        ram: 2,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3566_Linux,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Linux",
        cfwCompatibles: ["ArkOS", "AmberElec"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_Dk3aL67",
        enlaceDeCompra2: "",
        img: "x55",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    {
        nombre: "RK2023",
        fabricante: "Powkiddy",
        formato: "Horizontal",
        pantallaPulgadas: 3.5,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3500,
        procesador: "RK3566",
        ram: 1,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3566_Linux,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Linux",
        cfwCompatibles: ["ArkOS", "AmberElec"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DEUQrHD",
        enlaceDeCompra2: "",
        img: "rk2023",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    {
        nombre: "RGB30",
        fabricante: "Powkiddy",
        formato: "Horizontal",
        pantallaPulgadas: 4,
        pantallaRelacionAspecto: "1:1",
        pantallaResolucion: "720x720",
        bateria: 4100,
        procesador: "RK3566",
        ram: 1,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3566_Linux,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Linux",
        cfwCompatibles: ["ArkOS", "AmberElec"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DdWC2xv",
        enlaceDeCompra2: "",
        img: "rgb30",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },


    {
        nombre: "RGB20SX",
        fabricante: "Powkiddy",
        formato: "Vertical",
        pantallaPulgadas: 4,
        pantallaRelacionAspecto: "1:1",
        pantallaResolucion: "720x720",
        bateria: 4100,
        procesador: "RK3566",
        ram: 1,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3566_Linux,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Linux",
        cfwCompatibles: ["ArkOS", "AmberElec"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DFbymkx",
        enlaceDeCompra2: "",
        img: "rgb20sx",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    {
        nombre: "RGB10 MAX 3 Pro",
        fabricante: "Powkiddy",
        formato: "Horizontal",
        pantallaPulgadas: 5,
        pantallaRelacionAspecto: "16:9",
        pantallaResolucion: "854x480",
        bateria: 4000,
        procesador: "A311D",
        ram: 3,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 1000,
        plataformaPerfectaMax: "PSP/N64/DC",
        plataformasEmulables: ColeccionFull.filter(x => x.clave != 'SWITCH'),
        plataformasEmulablesSemaforo: RK3566_Android,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Linux JELOS",
        cfwCompatibles: ["RockNix"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_Dm0GWfp",
        enlaceDeCompra2: "",
        img: "rgb10max3pro",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    {
        nombre: "X28",
        fabricante: "Powkiddy",
        formato: "Horizontal",
        pantallaPulgadas: 5.5,
        pantallaRelacionAspecto: "16:9",
        pantallaResolucion: "1280x720",
        bateria: 5000,
        procesador: "T618",
        ram: 4,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 512,
        plataformaPerfectaMax: "PSP/N64/DC",
        plataformasEmulables: ColeccionFull,
        plataformasEmulablesSemaforo: T618,
        joysticks: 2,
        tactil: true,
        sistemaOperativoStock: "Android 11",
        cfwCompatibles: [],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DdpKqsb",
        enlaceDeCompra2: "",
        img: "x28",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },
    {
        nombre: "Pocket 3 Lite",
        fabricante: "Retroid",
        formato: "Horizontal",
        pantallaPulgadas: 4.7,
        pantallaRelacionAspecto: "16:9",
        pantallaResolucion: "750x1334",
        bateria: 4000,
        procesador: "T310",
        ram: 2,
        ram2: 3,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 32,
        almExterno: 512,
        plataformaPerfectaMax: "PSP/N64/DC",
        plataformasEmulables: ColeccionFull,
        plataformasEmulablesSemaforo: T310,
        joysticks: 2,
        tactil: true,
        sistemaOperativoStock: "Android 11",
        cfwCompatibles: [],
        enlaceDeCompra1: " https://s.click.aliexpress.com/e/_DFWkxs3",
        enlaceDeCompra2: "",
        img: "pocket3lite",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },

    {
        nombre: "Pocket 3 Plus",
        fabricante: "Retroid",
        formato: "Horizontal",
        pantallaPulgadas: 4.7,
        pantallaRelacionAspecto: "16:9",
        pantallaResolucion: "750x1334",
        bateria: 4500,
        procesador: "T618",
        ram: 4,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 128,
        almExterno: 512,
        plataformaPerfectaMax: "PSP/N64/DC",
        plataformasEmulables: ColeccionFull,
        plataformasEmulablesSemaforo: T618,
        joysticks: 2,
        tactil: true,
        sistemaOperativoStock: "Android 11",
        cfwCompatibles: [],
        enlaceDeCompra1: " https://s.click.aliexpress.com/e/_DCJrqTZ",
        enlaceDeCompra2: "",
        img: "pocket3plus",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack: true
    },
    {
        nombre: "Pocket 4 Pro",
        fabricante: "Retroid",
        formato: "Horizontal",
        pantallaPulgadas: 4.7,
        pantallaRelacionAspecto: "16:9",
        pantallaResolucion: "750x1334",
        bateria: 5000,
        procesador: "MediaTek Dimensity 1100",
        ram: 8,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 128,
        almExterno: 1000,
        plataformaPerfectaMax: "PSP/N64/DC",
        plataformasEmulables: ColeccionFull,
        plataformasEmulablesSemaforo: MTKD1100,
        joysticks: 2,
        tactil: true,
        sistemaOperativoStock: "Android 13",
        cfwCompatibles: [],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DDELD27",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DDi21e7",
        img: "pocket4pro",
        gatillosAnalogicos: true,
        joysticksHall: true,
        jack:true
    },


    // OTRAS
    {
        nombre: "K36",
        fabricante: "KinHank",
        formato: "Vertical",
        pantallaPulgadas: 3.5,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3500,
        procesador: "RK3326",
        ram: 1,
        hdmi: false,
        bt: false,
        wifi: false,
        dobleSlot: false,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3326,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Emuelec 4.7",
        cfwCompatibles: ["ArkOS"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_mr8Jkb2",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_msYXGTS",
        img: "k36",
        gatillosAnalogicos: false,
        joysticksHall: true,
        jack:true
    },
    {
        nombre: "Odin 2 Pro",
        fabricante: "AYN",
        formato: "Horizontal",
        pantallaPulgadas: 3.5,
        pantallaRelacionAspecto: "16:9",
        pantallaResolucion: "1920x1080",
        bateria: 8000,
        procesador: "Snapdragon 8 Gen2",
        ram: 12,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: false,
        almInterno: 256,
        almExterno: 1000,
        plataformaPerfectaMax: "PSP/N64/DC",
        plataformasEmulables: ColeccionFull,
        plataformasEmulablesSemaforo: SND8Gen2,
        joysticks: 2,
        tactil: true,
        sistemaOperativoStock: "Android 13",
        cfwCompatibles: [],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_Dls1mX5",
        enlaceDeCompra2: "",
        img: "odin2pro",
        gatillosAnalogicos: true,
        joysticksHall: true,
        jack:true
    },

    {
        nombre: "R36S",
        fabricante: "Otros",
        formato: "Vertical",
        pantallaPulgadas: 3.5,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3500,
        procesador: "RK3326",
        ram: 1,
        hdmi: false,
        bt: false,
        wifi: false,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3326,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "ArkOS",
        cfwCompatibles: ["AmberElec", "RockNix"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DlFTELH",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_Dlh9YWb",
        img: "r36s",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack:true
    },

    {
        nombre: "XU10",
        fabricante: "MagicX",
        formato: "Vertical",
        pantallaPulgadas: 3.5,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3000,
        procesador: "RK3326S",
        ram: 1,
        hdmi: false,
        bt: false,
        wifi: false,
        dobleSlot: true,
        almInterno: 0,
        almExterno: 256,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3326,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Linux (MagicX)",
        cfwCompatibles: ["AmberElec", "RockNix"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DFvMY31",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DdoTNP9",
        img: "xu10",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack:true
    },
    {
        nombre: "XU Mini M",
        fabricante: "MagicX",
        formato: "Horizontal",
        pantallaPulgadas: 2.8,
        pantallaRelacionAspecto: "4:3",
        pantallaResolucion: "640x480",
        bateria: 3000,
        procesador: "RK3562",
        ram: 1,
        hdmi: false,
        bt: false,
        wifi: false,
        dobleSlot: false,
        almInterno: 0,
        almExterno: 512,
        plataformaPerfectaMax: "PS1 / NDS",
        plataformasEmulables: Coleccion5ta,
        plataformasEmulablesSemaforo: RK3326,
        joysticks: 2,
        tactil: false,
        sistemaOperativoStock: "Linux (MagicX)",
        cfwCompatibles: [],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_Dm1wQdz",
        enlaceDeCompra2: "https://s.click.aliexpress.com/e/_DmfWT0P",
        img: "xuminim",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack:true
    },
    {
        nombre: "E6 Plus",
        fabricante: "GameMT",
        formato: "Horizontal",
        pantallaPulgadas: 5,
        pantallaRelacionAspecto: "16:9",
        pantallaResolucion: "1280x720",
        bateria: 5000,
        procesador: "RK3566",
        ram: 2,
        hdmi: true,
        bt: true,
        wifi: true,
        dobleSlot: true,
        almInterno: 32,
        almExterno: 512,
        plataformaPerfectaMax: "PSP/N64/DC",
        plataformasEmulables: ColeccionFull,
        plataformasEmulablesSemaforo: RK3566_Android,
        joysticks: 2,
        tactil: true,
        sistemaOperativoStock: "Linux (GameMT) / Android",
        cfwCompatibles: ["AmberElec"],
        enlaceDeCompra1: "https://s.click.aliexpress.com/e/_DmjSObp",
        enlaceDeCompra2: "",
        img: "e6plus",
        gatillosAnalogicos: false,
        joysticksHall: false,
        jack:true
    },


   


];

function writeIt(){
    fs.writeFile('./public/catalogos/consolas/consolasestoesretro.json', JSON.stringify(consolas), function(err){
        if(err){
            console.log("OK hubo un error: ", err);
        }
    });
}

writeIt()